# Environment variable keys
ENV_BUSINESS_PAYMENT_TABLE_NAME = 'BUSINESS_PAYMENT_TABLE_NAME'

# Cross-stack environment variable keys
IMPORTED_BUSINESS_PAYMENT_LAMBDA_ENV_VAR_KEY_TRANSACTIONS_TABLE_NAME = 'TRANSACTIONS_TABLE_NAME'
IMPORTED_BUSINESS_PAYMENT_LAMBDA_ENV_VAR_KEY_TUTOR_TRANSACTIONS_TABLE_NAME = 'TUTOR_TRANSACTIONS_TABLE_NAME'
IMPORTED_BUSINESS_PAYMENT_LAMBDA_ENV_VAR_KEY_TUTORS_TABLE_NAME = 'TUTORS_TABLE_NAME'
IMPORTED_BUSINESS_PAYMENT_LAMBDA_ENV_VAR_KEY_BUSINESS_INTERNAL_DEBTS_TABLE_NAME = 'BUSINESS_INTERNAL_DEBTS_TABLE_NAME'
IMPORTED_BUSINESS_PAYMENT_LAMBDA_ENV_VAR_KEY_DISCORD_API_SECRETS_ARN = 'IMPORTED_DISCORD_API_SECRETS_ARN'

# Secrets Manager keys
SECRET_KEY_DISCORD_BOT_TOKEN = 'bot_token'
SECRET_KEY_PAYMENT_REMINDERS_CHANNEL_ID = 'payment_reminders_channel_id'

# DynamoDB keys
DYNAMODB_KEY_UID = 'uid'
DYNAMODB_KEY_MONTH_START = 'month_start'
DYNAMODB_KEY_MONTH_END = 'month_end'
DYNAMODB_KEY_AHSAN_OWES_MUAZ = 'ahsan_owes_muaz'
DYNAMODB_KEY_MUAZ_OWES_AHSAN = 'muaz_owes_ahsan'
DYNAMODB_KEY_NET_AMOUNT = 'net_amount'
DYNAMODB_KEY_NET_OWED_TO = 'net_owed_to'
DYNAMODB_KEY_PROCESSED_DISCORD = 'processed_discord'
DYNAMODB_KEY_ITEM = 'Item'
DYNAMODB_KEY_TUTOR_ID = 'tutorId'
DYNAMODB_KEY_TUTOR_NAME = 'tutorName'
DYNAMODB_KEY_DEBT_TO = 'debtTo'
DYNAMODB_KEY_TRANSACTION_KEY = 'transactionKey'
DYNAMODB_KEY_ACTION_BY = 'actionBy'
DYNAMODB_KEY_AMOUNT = 'amount'
DYNAMODB_KEY_TIMESTAMP = 'timestamp'
DYNAMODB_KEY_TRANSACTION_TYPE = 'transactionType'

# DynamoDB operations
DYNAMODB_UPDATE_EXPRESSION = 'SET processed_discord = :val'

# Transactions
TRANSACTION_TYPE_DEBIT = 'DEBIT'
TRANSACTION_TYPE_CREDIT = 'CREDIT'
BUSINESS_PAYMENT_ACTION_BY = 'mathpracs-business-payment-reminder'

# Partners
PARTNER_AHSAN = 'ahsan'
PARTNER_MUAZ = 'muaz'
PARTNERS = (PARTNER_AHSAN, PARTNER_MUAZ)
PARTNER_DISPLAY_NAMES = {PARTNER_AHSAN: 'Ahsan', PARTNER_MUAZ: 'Muaz'}
PARTNER_SPLIT = 0.5

# Go-live date
GO_LIVE_DATE = '2026-09-13'

# UID prefix
UID_PREFIX = 'business'

# Timezone
TIMEZONE_CHICAGO = 'America/Chicago'

# Date format
DATE_FORMAT = '%Y-%m-%d'

# AWS service names
AWS_SERVICE_DYNAMODB = 'dynamodb'
AWS_SERVICE_SECRETSMANAGER = 'secretsmanager'

# Response messages
RESPONSE_MESSAGE_SUCCESS = 'MathPracs Business Payment Reminder executed successfully'
RESPONSE_MESSAGE_ALREADY_PROCESSED = 'MathPracs Business Payment Reminder already processed for this month'
RESPONSE_MESSAGE_NOTHING_TO_REPORT = 'MathPracs Business Payment Reminder had nothing to report'
RESPONSE_KEY_MESSAGE = 'message'
RESPONSE_KEY_RESULTS = 'results'
RESPONSE_KEY_ERROR = 'error'

# HTTP status codes
HTTP_STATUS_OK = 200
HTTP_STATUS_ERROR = 500
